[package]
name = "cli_greeter"
version = "0.1.0"
authors = ["Alejandro-Villa <awewanwo@disroot.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.12"
rand = "0.7.3"
